text_dict = { 't1': 'Big Bang Factory',
              't2': 'Welcome to Big Bang Factory',
              't3': 'Crea il tuo universo!',
              't4': 'Main',
              't5': 'New',
              't6': 'Save Movie',
              't7': 'Send',
              't8': 'Go Back',
              't9': 'Exit',
              't10': 'Pipeline',
              't11': 'Open',
              't12': 'Settings',
              't13': 'Email',
              't131' : 'Save Directory',
              't14': 'User Specifications',
              't15': 'Nome',
              't16': 'Email',
              't17': 'Mostra fotocamera',
              't18': 'Scatta foto',
              't19': 'Parametri cosmologici',
              't20': 'Energia Oscura',
              't21': 'Costante Cosmologica',
              't22': 'Quintessenza',
              't23': 'Phantom',
              't24': 'Materia Oscura',
              't25': 'Fredda',
              't26': 'Tiepida',
              't27': 'Universo Primordiale',
              't28': 'Naturale',
              't29': 'Positivo',
              't30': 'Negativo',
              't31': 'Teoria gravitazionale',
              't32': 'Einsteiniana',
              't33': 'Modificata',
              't34': 'Simulazione N-body',
              't35': 'Inizia simulazione',
              't351': 'Confronta simulazioni',
              't36': 'Lensing gravitazionale',
              't37': 'Mostra mappa di lensing',
              't38': 'Fotografia Lensing Debole',
              't39': 'Mostra lensing da ammasso',
              't40': 'Fotografia Lensing Forte',
              't41': 'Distanza lente-sorgente:',
              't42': "Questo e' l' universo di  ",
              't43': 'LookBack Time:',
              't44': 'Inserisci il tuo nome !!',
              't45': 'Email Credentials',
              't46': 'Email',
              't47': 'Password',
              't48': 'Submit',
              't49': 'Miliardi di anni fa',
              't50': 'Euclidea',
              't51': 'Sferica',
              't52': 'Iperbolica',
              't53': 'Geometria dello spazio'
              }
