text_dict = { 't1': 'Big Bang Factory',
              't2': 'Welcome to Big Bang Factory',
              't3': 'Click to Create Your Universe',
              't4': 'Main',
              't5': 'New',
              't6': 'Save',
              't7': 'Send',
              't8': 'Go Back',
              't9': 'Exit',
              't10': 'Pipeline',
              't11': 'Open',
              't12': 'Settings',
              't13': 'Email',
              't131' : 'Save Directory',
              't14': 'User Specifications',
              't15': 'Name',
              't16': 'Email',
              't17': 'Show CAM',
              't18': 'Take Photo',
              't19': 'Cosmological Parameters',
              't20': 'Dark Energy Type',
              't21': 'Constant',
              't22': 'Quintessence',
              't23': 'Phantom',
              't24': 'Dark Matter Type',
              't25': 'Cold',
              't26': 'Warm',
              't27': 'Initial Matter Distribution',
              't28': 'Gaussian',
              't29': 'Positive non-Gaussian',
              't30': 'Negative non-Gaussian',
              't31': 'Gravity Type',
              't32': 'Einstein',
              't33': 'Modified Garvity',
              't34': 'N-Body Simulation',
              't35': 'Simulation Run',
              't351': 'Simulation Compare',
              't36': 'Gravitational Lensing',
              't37': 'Show Lensing Map',
              't38': 'Map Lens User Face',
              't39': 'Show Lensing Cluster',
              't40': 'Cluster Lens User Face',
              't41': 'Source-Lens Distance:',
              't42': 'Simulation Maker',
              't43': 'LookBack Time:',
              't44': 'Please Enter Your Name !!',
              't45': 'Email Credentials',
              't46': 'Email',
              't47': 'Password',
              't48': 'Submit',
              't49': 'Billion Years Ago',
              't50': 'Flat',
              't51': 'Closed',
              't52': 'Open',
              't53': 'Space Curvature'
              }
